# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    container_name: Ecommerce-Postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
    networks:
      - web

  pgadmin:
    container_name: pgadmin
    links:
      - db
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - 8080:80
    volumes:
      - ./docker-data/pgadmin:/var/lib/pgadmin
    networks:
      - web

networks:
  web:
    driver: bridge
